config/routes.rb
Borrow::Application.routes.draw do
  root :to => "pages#home"
  get "about" => "pages#about"
  get "how_it_works" => "pages#how_it_works"
  get "sign_up" => "pages#sign_up"
  get "sign_in" => "pages#sign_in"
  resources :user
end

app/models/status.rb
class Status < ActiveRecord::Base
	belongs_to :user
end

app/models/user_wallet.rb
class UserWallet < ActiveRecord::Base
	belongs_to :user
end

app/models/users.rb
class Users < ActiveRecord::Base
	validates_uniqueness_of :email

  has_many :statuses
  has_one :user_wallet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController <ApplicationController
	def home
		end

		def about
		end

		def how_it_works
		end

		def sign_up
		end

		def sign_in
		end

end

app/controllers/user_crontroller.rb
class UserController<ApplicationController
	
	def new

	end


	def create
		@user = User.new(user_params)
		if @user.save
			flash[:notice] "your Account has been created"

		else
			flash[:notice] "Oops something went wrong"
		end
		redirect_to root_path

	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			flash[:notice] = "Your account was updated successfully."
		else
			flash[:notice] = "There was a problem updating your account"
		end
		redirect_to user_path(@user)
	end

	def destroy
		@user = User.find(params[:id])
		if @user.destroy
			flash[:notice] = "User has been successfully deleted"
		else
			flash[:notice] = "There was a problem deleting the user."
		end
		redirect_to user_index_path
	end


	def show
		@user = User.find(params[:id])
	end


	def index
		@users = User.all
	end


	private


	def user_params
		params.require(:user).permit(:email, :password, :name, :email, :phone,)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title Borrow.io
    = stylesheet_link_tag    "bootstrap", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "bootstrap", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body.container
  .navbar
    %a.navbar-brand{:href => "/"} Borrow.io
    %ul.nav.navbar-nav
      %li.active
        =link_to "Home", root_path
      %li
        =link_to "About", about_path
      %li
        =link_to "How It Works", how_it_works_path
      
  = yield

app/views/pages/about.haml
%h3 About

app/views/pages/home.haml
.jumbotron
  %h1 Hello, world!
  %p ...
  %p
    =link_to "Sign Up", new_user_path, {:class => "btn btn-primary btn-large"}

app/views/pages/how_it_works.haml
%h3 How It Works

app/views/pages/sign_in.haml
%h3 Sign In

app/views/pages/sign_up.haml
%h3 sign up

app/views/users/_form.haml
=f.label :name
=f.text_field :name
=f.label :email
=f.text_field :email
=f.label :password
=f.password_field :password
=f.submit

app/views/users/edit.haml
%h1 Edit your Profile
=form_for @user do |f|
	=render "form", {f: f}

app/views/users/index.haml
%h1 All Users
-@users.each do |user|
	%h3=user.name
	%h3=user.email
	=link_to "Delete User", user_path(user), :method => :delete

app/views/users/new.haml
%h1 Sign Up 
=form_for User.new, :url ="/user" do |f|
	=render "form", {f: f}

app/views/users/show.haml
%h1 
  User Profile for
  =@user.name
 %h3 Email
 =@user.email